name: Release Docker Image
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: pyama86
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: pyama
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/pyama86/ngx_waitingroom:${{ github.sha }}
      -
        name: Build and push viron
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./viron
          tags: ghcr.io/pyama86/viron:${{ github.sha }}
